[package]
name = "fedramp-scraper"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
csv = "1.3.1"
thirtyfour = "0.35.0"
tokio = { version = "1.44.1", features = ["rt-multi-thread"] }
